# Enable the H2 Web UI
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Database Connection Info
# Use these fields to access the database directly from your browser
# Use the localhost:8080 IP and Port, and then the path above.
spring.datasource.url=jdbc:h2:mem:studentdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Show SQL in the console (great for student debugging)
spring.jpa.show-sql=true